# Generated by Django 4.0.3 on 2022-03-30 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0001_initial'),
        ('posts', '0002_post_text_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='icons.icon', verbose_name='Ícone'),
        ),
    ]
